name: 'Detox CI Tests'
on: [push]

jobs:
  tests:
    name: 'Running tests'
    runs-on: 'macOS-latest'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.6
      - name: Setup - Install Homebrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Setup - Install Yarn
        run: brew install yarn --ignore-dependencies
      - name: Setup - Install NPM Dependencies
        run: yarn
      - name: Setup - Install CocoaPods CLI
        run: sudo gem install cocoapods
      - name: Run tests
        run: yarn ci
