name: 'Detox CI Tests'
on: [push]

jobs:
  tests:
    name: 'Running Detox CI tests'
    runs-on: 'macOS-latest'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.6
      - name: Setup - Install CocoaPods CLI
        run: sudo gem install cocoapods
      - name: Run tests
        run: npm run ci
